# Generated by Django 6.0.2 on 2026-02-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_optimizer', '0003_routecache_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routecache',
            name='geometry',
            field=models.JSONField(default=dict),
        ),
    ]
