# Generated by Django 6.0.2 on 2026-02-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('total_slots', models.IntegerField()),
                ('fast_charger', models.BooleanField(default=False)),
                ('power_kw', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EVVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('battery_capacity_kwh', models.FloatField()),
                ('max_range_km', models.FloatField()),
                ('efficiency_km_per_kwh', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TripHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('distance_km', models.FloatField()),
                ('battery_used_percentage', models.FloatField()),
                ('charging_stops', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
