# Generated by Django 6.0.2 on 2026-02-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_lon', models.FloatField()),
                ('source_lat', models.FloatField()),
                ('dest_lon', models.FloatField()),
                ('dest_lat', models.FloatField()),
                ('distance_km', models.FloatField()),
                ('duration_min', models.FloatField()),
            ],
            options={
                'unique_together': {('source_lon', 'source_lat', 'dest_lon', 'dest_lat')},
            },
        ),
    ]
