# Generated by Django 6.0.2 on 2026-02-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_optimizer', '0002_routecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='routecache',
            name='geometry',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
